version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    # networks:
    #   - server-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    # networks:
    #   - server-network
  worker:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        APP_NAME: worker
    ports:
      - 3000:3000
    # networks:
    #   - server-network
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MONGODB_CONNECTION: 'mongodb://root:root@mongo:27017/Pizza?authSource=admin'
      MONGODB_USER: 'root'
      MONGODB_PASSWORD: 'root'
# networks:
#   server-network: